### ISSUE TITLE
Types behaving incorrectly on Linux compared to Windows 10?

### ISSUE THREAD

**Issue by DexterHill0** [Spu7Nix/SPWN-language#117]
In my BMP parser I read a file and create the `@data` class using the read data like so:
```
let data = @data::new($.readfile(file, "bin"))
```
The data class is this (it's very similar to `@file` but it works with arrays not strings)
```
type @data
impl @data {
	read: (self, amount: @number) {
		let data = @data::new(self.d[self.p : self.p+amount])
		self.p += amount
		return data
	},

	move: (self, pos: @number) {
		self.p += pos
	},

	raw: (self) {
		return self.d
	},

	is_eof: (self) {
		return self.p >= self.d.length
	},

	new: (data: [@number]) {
		return @data::{
			d: data,
			length: data.length,
			p: 0
		}
	}
}
```
The `data` variable is then passed to different classes like `@bmp_fhdr::new(self.raw)` where `self.raw` has the type `@data`. These classes have a `new` method like so, in which they can only take an argument of type `@data`:
```
new: (data: @data)
```

On my machine running Windows 10 with SPWN 0.6 no matter what BMP I parse, I have no issue with a this. However a user (`TeaWhyDee#7121` on Discord) let me know that they get this error using the library and parsing BMPs (they use Linux and not Windows 10, but do use SPWN 0.6):
```
Error: Pattern mismatch
     ╭─[test.spwn:15:7]
     │
  15 │ bmp = spwnbmp.parse_bmp("../../image/iamge2.bmp")
     ·       ──────────────────────┬──────────────────────
     ·                             ╰──────────────────────── 1: Error comes from this macro call
     │
     ├─[/home/<...>/Documents/scripts/gd/libraries/spwn_bmp/bmp.spwn:505:32]
     │
  81 │         new: (data: @data) {
     ·                     ──┬──
     ·                       ╰──── 4: Pattern defined as @data here
 505 │            file_header = @bmp_fhdr::new(self.raw)
     ·                                         ────┬───
     ·                                             ╰───── 5: Expected @data, found type_indicator
 530 │ ╭─:arrow_forward:        return @bmp::{
 535 │ ├─:arrow_forward:        }
     · │
     · ╰────────────── 3: Value defined as type_indicator here
 548 │         bmp._parse()
     ·         ──────┬─────
     ·               ╰─────── 2: Error comes from this macro call
```
Even if I remove the type definition on the arguments like:
```
new: (data)
```
There is still an error instead it's just:
```
1: Error comes from this macro call
     │
     ├─[/home/<...>/Documents/scripts/gd/libraries/spwn_bmp/bmp.spwn:84:21]
     │
  84 │        let file_header = data.read(@bmp_fhdr::SIZE)
     ·                          ─────────────┬────────────
     ·                                       ╰────────────── 4: 'read' is undefined
 505 │        file_header = @bmp_fhdr::new(self.raw)
     ·                      ────────────┬───────────
     ·                                  ╰───────────── 3: Error comes from this macro call
 548 │     bmp._parse()
     ·     ──────┬─────
     ·           ╰─────── 2: Error comes from this macro call
```

Is this a bug in the Linux version of SPWN?

**Comment by sertdfyguhi** [comment]
maybe he is not using the latest version of spwn?

**Comment by DexterHill0** [comment]
> 
> 
> maybe he is not using the latest version of spwn?

I did ask and they said they were using the latest release (0.6), They also tried compiling the latest version from source but got the same error.

**Comment by sertdfyguhi** [comment]
maybe you're not using the latest version of spwn

**Comment by sertdfyguhi** [comment]
it doesn't work because the argument he is passing in is not a `@data` type

**Comment by DexterHill0** [comment]
> 
> 
> it doesn't work because the argument he is passing in is not a `@data` type

But they don't pass the data type themselves. The second line of the OP is:
```
```

**Comment by sertdfyguhi** [comment]
can you send the code?

**Comment by DexterHill0** [comment]
> 
> 
> can you send the code?

https://github.com/DexterHill0/spwn-bmp/tree/main/spwn_bmp
