### ISSUE TITLE
Mac BlockModeError for building levels

### ISSUE THREAD

**Issue by PhantomXDLOL** [Spu7Nix/SPWN-language#123]
I was making a simple test program that looks like this 
`bob = 4g
on(touch(), !{
    bob.move(x = 10, y = 20, duration = 0.5, easing = EASE_IN_OUT)
})`
When I went to build it, I used `spwn build -n "spwn"`. (same thing happens without -n or when I add -s [CCLocalLevels path])
I got an error saying `Error reading level:
BlockModeError`

Please keep in mind this is on mac. Thank you for your help.

**Comment by sertdfyguhi** [comment]
you need to build the file like `spwn build path/to/spwn/file.spwn -n "spwn"`

**Comment by PhantomXDLOL** [comment]
I already have tried that. All I did for the top one was cd path/to/spwn. Then run the build command.

**Comment by feverdreme** [comment]
What OS are you?

**Comment by sertdfyguhi** [comment]
look title

**Comment by feverdreme** [comment]
does the "spwn" level already exist in gd? You need to initialize it by actually creating the level in game then spwn can do its stuff

**Comment by PhantomXDLOL** [comment]
Yes. The level exists.

**Comment by feverdreme** [comment]
Did you turn off gd before running spwn?
