### ISSUE TITLE
Visual block editor? | Help

### ISSUE THREAD

**Issue by DabDatBass** [Spu7Nix/SPWN-language#129]
Hey there, I was looking at [https://spu7nix.net/spwn/#/triggerlanguage/7selectorpanel](this) when I realized that the font used in the first image isn't the font in Geometry Dash. Is there a certain visual block editor or some preset setting I can turn on? (Visual Studio Code)

thanks 🍡

**Comment by SpeckyYT** [comment]
> Hey there, I was looking at https://spu7nix.net/spwn/#/triggerlanguage/7selectorpanel when I realized that the font used in the first image isn't the font in Geometry Dash.

Why should the docs have the same font as in ​Geometry Dash?

> Is there a certain visual block editor

[BLCK](https://github.com/FlowVix/BLCK), but it isn't usable for end-users yet

> or some preset setting I can turn on? (Visual Studio Code)

There is the SPWN extension in VSCode

**Comment by feverdreme** [comment]
[SPWN vscode extension](https://marketplace.visualstudio.com/items?itemName=Spu7Nix.spwn-language-support)

there are also extensions for vim and sublime

**Comment by Fl1pNatic** [comment]
> > Hey there, I was looking at https://spu7nix.net/spwn/#/triggerlanguage/7selectorpanel when I realized that the font used in the first image isn't the font in Geometry Dash.
> 
> Why should the docs have the same font as in ​Geometry Dash?
> 
This font is actually in the game as an info font
![image](https://user-images.githubusercontent.com/41564630/132122043-efa73a76-cf65-4a0e-b9f6-a3e3469f1cf2.png)

**Comment by Spu7Nix** [comment]
If you mean the little tooltip that appears when selecting objects in geometry dash, you enable it by checking the "show object info" box in the gd editor pause menu.
[](https://user-images.githubusercontent.com/50080834/132122242-20b35059-cf8e-4d58-ab17-290ac7b24893.jpg)
