### ISSUE TITLE
What is the empty feature in the installer?

### ISSUE THREAD

**Issue by kotenok2000** [Spu7Nix/SPWN-language#131]
![Снимок экрана (60)](https://user-images.githubusercontent.com/8822292/132129357-101374ce-3733-493d-99b6-cf1f96c4ad42.png)

**Comment by SpeckyYT** [comment]
I also noticed it, but never cared 😂

**Comment by Fl1pNatic** [comment]
I was almost baited to say "Why are you using Windows XP" but then I saw the window

**Comment by Spu7Nix** [comment]
Fixed in commit 8085ddf
