### ISSUE TITLE
variable typo

### ISSUE THREAD

**Issue by approachcircle** [Spu7Nix/SPWN-language#137]
https://github.com/Spu7Nix/SPWN-language/blob/046d081de619690ad1c760ee00dc6ce7aa6b7adb/test/test.spwn#L2
should print the variable defined as "hello" not "helol" which is undefined

**Comment by SpeckyYT** [comment]
That's the point of that test code.
It tries to search for the most similar variables in the current context (v0.7 goes brr).

**Comment by approachcircle** [comment]
ohhhh my bad
