### ISSUE TITLE
visual studio code doesn't recognize the term "spwn" when building help

### ISSUE THREAD

**Issue by UltroGmr** [Spu7Nix/SPWN-language#165]
PS C:\Users\Ultro> spwn build easingmove.spwn
spwn : The term 'spwn' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the     
path is correct and try again.
At line:1 char:1
+ spwn build easingmove.spwn
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (spwn:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sertdfyguhi** [comment]
SPWN is not in the PATH environment variable
