### ISSUE TITLE
Error For Compile Pi.spwn

### ISSUE THREAD

**Issue by cheznewa** [Spu7Nix/SPWN-language#169]
I Cant Compile :::: [pi.spwn](https://github.com/adafcaefc/pi.spwn/blob/main/pi.spwn)
because The error is "speed is undefined"

full message ::::::
```
Error: Use of undefined macro argument
    ╭─[pi.spwn:20:14]
    │
 20 │     t2.reset(speed = 12)
    ·              ─────┬────
    ·                   ╰────── 'speed' is undefined
────╯
```

**Comment by sertdfyguhi** [comment]
pi.spwn is bad code

**Comment by SpeckyYT** [comment]
`counter.reset()` used to be slow, but now it happens instantly, so you can remove the `speed = 12` in resets

**Comment by camila314** [comment]
assuming issue was fixed after `speed = 12` was removed
