### ISSUE TITLE
Feat: `#[empty]` attribute on `@type`s

### ISSUE THREAD

**Issue by krista-chan** [Spu7Nix/SPWN-language#244]
# `#[empty]`

## Information

This will be an attribute that can be applied to `type @type` statements. This will make the type function much like [rust's unit structs](https://doc.rust-lang.org/std/keyword.struct.html)

Applying this attribute means it will never have any properties on it. While you will able to implement methods, an instance of `@type` will not hold any data. Instantiation will be simplified to just the type's name, eliminating the trailing `::{}` needed to instantiate currently empty structs such as `@null`

**Comment by Spu7Nix** [comment]
`@number` or `@string` are already instances of the type `@type_indicator`, but either way i don't really see how this would be useful. Would it just error if you add any additional values?
