### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Endermaster3690** [Spu7Nix/SPWN-language#261]
i did the spwn setup wizard

where'd it install

**Comment by SpeckyYT** [comment]
it probably happens when you do it.

but i guess it's fine.

**Comment by Endermaster3690** [comment]
> it probably happens when you do it.
> 
> but i guess it's fine.

i don't understand

**Comment by SpeckyYT** [comment]
spwn gets installed where you selected to install it

**Comment by Endermaster3690** [comment]
ok i'm opening C:/Program Files/spwn.exe

and it don't wanna open :((((

**Comment by Endermaster3690** [comment]
> join the discord server if you haven't already https://discord.gg/xqny9rX9hA we'll be able to help you much better there

uhh i'm not 13

**Comment by SpeckyYT** [comment]
> > join the discord server if you haven't already https://discord.gg/xqny9rX9hA we'll be able to help you much better there
> 
> uhh i'm not 13

I am also not 13, don't worry ;)

**Comment by Endermaster3690** [comment]
if i joined, that'd violate discord rules and I'd be required a ban

**Comment by itsmebombie** [comment]
> > > join the discord server if you haven't already https://discord.gg/xqny9rX9hA we'll be able to help you much better there
> > 
> > 
> > uhh i'm not 13
> 
> I am also not 13, don't worry ;)

no way skeppy reveal pls abn😳😳😳😳

**Comment by SpeckyYT** [comment]
Don't you realize that you wouldn't be allowed to create an account on the entire internet at that age? 💀

The "13 years" rule isn't only valid on discord, but everywhere where people can save data about you, (for example, scratch, github, basically everywhere)

**Comment by Endermaster3690** [comment]
> Don't you realize that you wouldn't be allowed to create an account on the entire internet at that age? 💀
> 
> The "13 years" rule isn't only valid on discord, but everywhere where people can save data about you, (for example, scratch, github, basically everywhere)

ok

**Comment by itsmebombie** [comment]
> Don't you realize that you wouldn't be allowed to create an account on the entire internet at that age? 💀
> 
> The "13 years" rule isn't only valid on discord, but everywhere where people can save data about you, (for example, scratch, github, basically everywhere)

scratch💀 pretty sure you can create one on scratch (at least with parental permission)

**Comment by itsmebombie** [comment]
but yeah thats true

**Comment by Endermaster3690** [comment]
> but yeah thats true

![_51322005_okmont_thinks_464](https://user-images.githubusercontent.com/80355301/170771836-1e2adf52-bb82-4fee-a61d-15ef138b3dad.jpg)

**Comment by SpeckyYT** [comment]
tbh, the decision is yours, do whatever you want.

**Comment by itsmebombie** [comment]
true

**Comment by kr8gz** [comment]
well now after telling everyone your age there is a good decision and a not so good one

**Comment by itsmebombie** [comment]
> well now after telling everyone your age there is a good decision and a not so good one

i dont think there are people who care that much here to take out of theit time to report them to moderators

**Comment by Endermaster3690** [comment]
> well now after telling everyone your age there is a good decision and a not so good one

aight



> tbh, the decision is yours, do whatever you want.

![ok-3d-people-men-person-with-word-ok-stock-illustration_csp10450569 (1) webp](https://user-images.githubusercontent.com/80355301/170772287-3f18857f-d359-40a8-8fb9-34c13b1c4694.png)

**Comment by SpeckyYT** [comment]
(ig this issue can be closed... @krista-chan)

**Comment by Rudxain** [comment]
> > well now after telling everyone your age there is a good decision and a not so good one
> 
> i dont think there are people who care that much here to take out of theit time to report them to moderators

Unless we were on Twitter lol. People there are savages
