### ISSUE TITLE
Panic (ParseIntError) when trying to compile empty and non-empty scripts

### ISSUE THREAD

**Issue by SolarCityPower** [Spu7Nix/SPWN-language#276]
Hi, this issue has appeared seamingly at random today, and I've had the compiler fully working for a couple weeks now. Whenever I try compiling a script (in the script dir, by running `spwn b "name.spwn"`), whether the script is empty or not, i get the following error after the _Building script ..._ phase:
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', compiler\src\parse_levelstring.rs:33:42```
Full stacktrace [here](https://pastebin.com/gUBc4Gwg) if needed.

What I've tried in order to fix this:
- Basic things (repairing my install, manually uninstalling and reinstalling, and rebooting my pc)
- Running with sudo

I am on Windows 10 64 bit update 21H1 running spwn version 0.0.8
Thanks in advance for the help, and I'll provide more information if required.

**Comment by DexterHill0** [comment]
If you want to run a script without building to a level, make sure to use the `-l` flag (`spwn b "name.spwn" -l`). Without the flag, spwn will build to the first level (top of the list) in your created levels. Chances are there's a startpos in that level and so spwn is crashing while parsing the level data. It may also be there are manually placed objects with HSV which can sometime cause spwn to crash.
