### ISSUE TITLE
SPWN Playground Not Working

### ISSUE THREAD

**Issue by kryllyxofficial01** [Spu7Nix/SPWN-language#284]
I don't know whether it just isn't finished or if it genuinely isn't working for me, but when I go to the link provided (https://spu7nix.net/spwn/try/), I just a bunch of boxes and buttons that do nothing (see image below). If anyone could provide an explanation, that would be awesome.
<br>
![here](https://user-images.githubusercontent.com/97801783/193140332-6252655a-d19c-48b9-a25a-51fe46c0a481.jpeg)

**Comment by Spu7Nix** [comment]
that one is outdated, the new one can be found [here](https://spu7nix.net/spwn/playground/)

**Comment by kryllyxofficial01** [comment]
Thanks
