### ISSUE TITLE
Ignore item ID limit

### ISSUE THREAD

**Issue by Milk-Cool** [Spu7Nix/SPWN-language#286]
`Error: "This level exceeds the item ID limit! (4096/999)"`

How do I get around this? It doesn't seem to be a big issue. I don't want to recompile the whole thing myself just to get around this!

**Comment by itsmebombie** [comment]
you can only use 999 item ids per level. try reducing the script's item id usage

**Comment by Milk-Cool** [comment]
> you can only use 999 item ids per level. try reducing the script's item id usage

I can't. I need 4096 pickup triggers in my level.

Why do I need to use 999 item IDs anyways? Geometry Dash seems to handle more just fine

**Comment by kr8gz** [comment]
what are you even trying to do

**Comment by itsmebombie** [comment]
> > you can only use 999 item ids per level. try reducing the script's item id usage
> 
> I can't. I need 4096 pickup triggers in my level.
> 
> Why do I need to use 999 item IDs anyways? Geometry Dash seems to be able to handle more just fine

robtop moment

**Comment by Milk-Cool** [comment]
> what are you even trying to do

use pickup triggers as memory units for an emulator

1 trigger = 1 byte

**Comment by itsmebombie** [comment]
you know that counters can store more than a byte, right?

**Comment by Milk-Cool** [comment]
it's just way easier this way

**Comment by Milk-Cool** [comment]
I mean, if it's the only option here...

**Comment by Milk-Cool** [comment]
what's the max value?

**Comment by SpeckyYT** [comment]
2^31-1

**Comment by itsmebombie** [comment]
the other option is to use way less coutners

**Comment by itsmebombie** [comment]
> what's the max value?

the max safe value is ~`2^26`

**Comment by itsmebombie** [comment]
gd takes a huge time to load big numbers

**Comment by SpeckyYT** [comment]
> gd takes a huge time to load big numbers

I tested adding `2^31-1` to a counter, and it took around 15 seconds in 2.1

**Comment by itsmebombie** [comment]
thats huge time

**Comment by Milk-Cool** [comment]
> > what's the max value?
> 
> the max safe value is ~`2^26`

then uhhh ig i can only use 26 bits per trigger, 3 bytes
meaning i would need to use 1366 triggers which is still much more than i need

**Comment by Milk-Cool** [comment]
btw do you know if someone made a chip8 emulator in gd already?

**Comment by itsmebombie** [comment]
i'd guess bestgamer08 but he's banned on github

**Comment by itsmebombie** [comment]
he does all sorts of things

**Comment by Milk-Cool** [comment]
id? if you have it

**Comment by Milk-Cool** [comment]
also sorry for my terrible english

**Comment by itsmebombie** [comment]
> > > what's the max value?
> > 
> > 
> > the max safe value is ~`2^26`
> 
> then uhhh ig i can only use 26 bits per trigger, 3 bytes meaning i would need to use 1366 triggers which is still much more than i need

you can always reduce the mem size to 3kb

**Comment by SpeckyYT** [comment]
> what's the max value?

what do you mean? in spwn or gd?

in spwn (v0.8) it's around `(+-) 2^53` and in gd (2.1) it's `2^31-1`

**Comment by itsmebombie** [comment]
> id? if you have it

i'm not sure if he has ever done it but there is a pretty big chance

**Comment by Milk-Cool** [comment]
> > > > what's the max value?
> > > 
> > > 
> > > the max safe value is ~`2^26`
> > 
> > 
> > then uhhh ig i can only use 26 bits per trigger, 3 bytes meaning i would need to use 1366 triggers which is still much more than i need
> 
> you can always reduce the mem size to 3kb

chip8 memory size is 4kib sadly

**Comment by itsmebombie** [comment]
> > > > > what's the max value?
> > > > 
> > > > 
> > > > the max safe value is ~`2^26`
> > > 
> > > 
> > > then uhhh ig i can only use 26 bits per trigger, 3 bytes meaning i would need to use 1366 triggers which is still much more than i need
> > 
> > 
> > you can always reduce the mem size to 3kb
> 
> chip8 memory size is 4kib sadly

you can try using collision blocks for the remaining memory

**Comment by itsmebombie** [comment]
im not sure how efficient they would be tho

**Comment by SpeckyYT** [comment]
(btw, join [the discord server](https://discord.gg/qKZAhKXqgw), so we can discuss more easily 😎)

**Comment by itsmebombie** [comment]
true

**Comment by Milk-Cool** [comment]
> (btw, join [the discord server](https://discord.gg/qKZAhKXqgw), so we can discuss more easily sunglasses)

i don't have discord installed rn
sorry

**Comment by itsmebombie** [comment]
https://discord.gg/

**Comment by SpeckyYT** [comment]
> > (btw, join [the discord server](https://discord.gg/qKZAhKXqgw), so we can discuss more easily sunglasses)
> 
> i don't have discord installed rn sorry

discord also works on browser 💀 (it was actually primarely made for that)

**Comment by itsmebombie** [comment]
ikr

**Comment by Milk-Cool** [comment]
> im not sure how efficient they would be tho

1 bit per two blocks

65536 objects just for memory



nah thanks

**Comment by itsmebombie** [comment]
real

**Comment by Milk-Cool** [comment]
> > > (btw, join [the discord server](https://discord.gg/qKZAhKXqgw), so we can discuss more easily sunglasses)
> > 
> > 
> > i don't have discord installed rn sorry
> 
> discord also works on browser skull (it was actually primarely made for that)

oh yeah right, i just forgor for a moment

**Comment by itsmebombie** [comment]
i imagine that you could do it with n bits+1

**Comment by itsmebombie** [comment]
still not efficient but its way better than 65k blocks

**Comment by Milk-Cool** [comment]
sorry i have to go, see ya in discord ig

Milk_Cool#7881

**Comment by itsmebombie** [comment]
real

**Comment by Milk-Cool** [comment]
hopping onto discord

**Comment by Milk-Cool** [comment]
#general

**Comment by Milk-Cool** [comment]
![image](https://user-images.githubusercontent.com/43724263/200139624-aba1af2a-2e43-43ae-8296-f3d3df9146db.png)

I was able to bypass this by manually editing the source code.

`compiler/src/leveldata.rs`
line 294
`const ID_MAX: u16 = 999;`
