### ISSUE TITLE
build failiur

### ISSUE THREAD

**Issue by Github-epic-and-epic** [Spu7Nix/SPWN-language#288]
when i try to build spwn (i am writing spwn build), i get an error in the terminal saying “spwn : the term ‘spwn’ is not recognised as the name of a cmdlet, function, script file or openable program.” there is more but that should be enough

**Comment by SpeckyYT** [comment]
that's because you didn't install it (or you didn't reboot your pc)

**Comment by Github-epic-and-epic** [comment]
ive done both but still, to no avail
btw sorry for the failure spelling mistake

**Comment by Github-epic-and-epic** [comment]
oh nvm, i installed it but i installed the language code or whatever lol

**Comment by Github-epic-and-epic** [comment]
okay, so it it is working now, but when i put spwn build INSERTFILENAMEHERE.spwn it doesnt work, although i have the exact same name as the file, i'll post the error here

**Comment by Github-epic-and-epic** [comment]
the error: Error: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
although i have the file that it needs

**Comment by SpeckyYT** [comment]
what's your current working directory, and where is that file located

**Comment by Github-epic-and-epic** [comment]
the file is located in windows, spwn stuff (a folder i made) and also, what exactly do you mean by working directory? (sorry, im shit with computers)

**Comment by SpeckyYT** [comment]
open your folder where your .spwn file is located, then click on the top tab that shows the path, and type in it `cmd` and hit enter, so you're sure you have the same working directory

**Comment by Github-epic-and-epic** [comment]
yeah, they are in the same directory

**Comment by Github-epic-and-epic** [comment]
thanks specky it works now

**Comment by sertdfyguhi** [comment]
fucking close it then you piece

**Comment by Github-epic-and-epic** [comment]
i forgor
