### ISSUE TITLE
no worky

### ISSUE THREAD

**Issue by olliequaas** [Spu7Nix/SPWN-language#300]
whenever i try to open spwn.exe it immeadietly closes and never loads hardly anything

**Comment by RealSput** [comment]
SPWN is a CLI tool, so you'll have to run SPWN by opening "cmd.exe" (or Terminal if you're in MacOS/Linux)

**Comment by Spu7Nix** [comment]
Hi! SPWN is a CLI (command line interface), you use it by running the `spwn` command in a terminal. You can learn more about how SPWN works by reading the [docs](https://spu7nix.net/spwn/)!

**Comment by RealSput** [comment]
je moeder
