### ISSUE TITLE
List of SPWN pkg managers

### ISSUE THREAD

**Issue by TechStudent10** [Spu7Nix/SPWN-language#301]
In one of the more recent videos about SPWN, Spu7nix mentioned that people were building their own package managers for SPWN. I think some lists of them should be included in the README.

**Comment by SpeckyYT** [comment]
PCKP (pronounced pickup) is the name of the spwn package manager. It's built-in in spwn, in the current version (v0.8) it's... functional, but it doesn't work that well. In the rewrite (v0.9), we will also probably see PCKP getting rewritten with a better user experience than currently.

**Comment by TechStudent10** [comment]
> PCKP (pronounced pickup) is the name of the spwn package manager. It's built-in in spwn, in the current version (v0.8) it's... functional, but it doesn't work that well. In the rewrite (v0.9), we will also probably see PCKP getting rewritten with a better user experience than currently.

Ah. How do you access it?

**Comment by SpeckyYT** [comment]
> > PCKP (pronounced pickup) is the name of the spwn package manager. It's built-in in spwn, in the current version (v0.8) it's... functional, but it doesn't work that well. In the rewrite (v0.9), we will also probably see PCKP getting rewritten with a better user experience than currently.
> 
> Ah. How do you access it?

Look at the [ANMT repository](https://github.com/SpeckyYT/ANMT/), there is a file called `pckp.yaml`, and that's everything you need to do stuff with pckp (yeah, there is no way to access it, the only thing you can do is creating a `pckp.yaml` file and hoping it works).

The v0.8 pckp is really 🤢🤢 I suggest you to NOT use it, it's extremely painful and buggy.

**Comment by TechStudent10** [comment]
When will it be ready/completed/not 🤢🤢?

**Comment by SpeckyYT** [comment]
Whenever RWRT (rewrite) is.

**Comment by TechStudent10** [comment]
Alright
