### ISSUE TITLE
Division for large numbers are inaccurate.

### ISSUE THREAD

**Issue by sertdfyguhi** [Spu7Nix/SPWN-language#309]
Division for large numbers are inaccurate.
```rs
4549486090393983500 / 2
```
Returns `2274743045196991700` in SPWN when it should return `2274743045196991750`.

fix in rwrtrt

**Comment by Spu7Nix** [comment]
This is because SPWN uses floating point numbers. In the next version integers and floats are separate, which should fix this.

**Comment by sertdfyguhi** [comment]
ok thanks sput
