### ISSUE TITLE
error

### ISSUE THREAD

**Issue by youmustp** [Spu7Nix/SPWN-language#315]
error: Found argument 'Files\spwn\spwn.spwn' which wasn't expected, or isn't valid in this context

USAGE:
    spwn build [OPTIONS] <SCRIPT>

For more information try --help

**Comment by SpeckyYT** [comment]
it literally tells you the usage

**Comment by youmustp** [comment]
but it says Save the file, then open a terminal and type in "spwn build YOURFILENAME.spwn." Make sure to have GD closed during this process. After running this command, open GD, and the levels content will be modified. Head over to the docs to learn how to program in SPWN.

**Comment by itsmebombie** [comment]
💀 exacrly

**Comment by itsmebombie** [comment]
your file path probably has a space in it, try surrounding it in "

**Comment by youmustp** [comment]
it worked

**Comment by itsmebombie** [comment]
nice
