### ISSUE TITLE
Visual studio code not recognizing 'build' as a command

### ISSUE THREAD

**Issue by Squishberg** [Spu7Nix/SPWN-language#328]
![spwn help](https://github.com/Spu7Nix/SPWN-language/assets/144853297/6ea4ee2d-869d-4f9c-b6a0-ea924f475bef) have the plugin installed and spwn installed yet i get this error, can anyone help?

**Comment by SpeckyYT** [comment]
you shouldn't put the command line arguments in the file

**Comment by Squishberg** [comment]
how exactly do i do that?

**Comment by SpeckyYT** [comment]
go into the file `geometrize.spwn` and delete `spwn build <etc>`

**Comment by Squishberg** [comment]
Thank you so much, I appreaciate the help
