### ISSUE TITLE
Error reading level: Encoded text cannot have a 6-bit remainder.

### ISSUE THREAD

**Issue by PG24Official** [Spu7Nix/SPWN-language#332]
I don't know what this means can someone please help :'(

**Comment by SpeckyYT** [comment]
open gd, close gd, and rerun spwn

**Comment by PG24Official** [comment]
> open gd, close gd, and rerun spwn

I don't even have gd open at the minute

**Comment by PG24Official** [comment]
> open gd, close gd, and rerun spwn

showing the same message >_<
```
Parsing ...
Reading savefile...
Error reading level:
Encoded text cannot have a 6-bit remainder.
```

**Comment by ivythegreenest** [comment]
close it using the close button on the main menu instead of on the actual window handle

**Comment by PG24Official** [comment]
> close it using the close button on the main menu instead of on the actual window handle

It's showing a new error which is progress but not great

```
Parsing ...
Reading savefile...
Building script ...
———————————————————————————

Error: Couldn't find module file (./lib\../pckp_libraries/canvas)
   ╭─[example.spwn:1:1]
   │
 1 │ import './lib/'
   · ───────┬───────
   ·        ╰───────── Error when running this library/module
───╯
```

**Comment by SpeckyYT** [comment]
bro's seriously using ANMT

**Comment by PG24Official** [comment]
> bro's seriously using ANMT

Why is there a better video to gd level converter? :/

**Comment by SpeckyYT** [comment]
There is no better video to gd converter written in spwn.

I won't give any support for ANMT, since a ton of people don't even know how spwn works and just steal my project to compile nsfw videos to gd, and then blame me obviously. Good luck figuring out how ANMT works 👍

**Comment by PG24Official** [comment]
> There is no better video to gd converter written in spwn.
> 
> I won't give any support for ANMT, since a ton of people don't even know how spwn works and just steal my project to compile nsfw videos to gd, and then blame me obviously. Good luck figuring out how ANMT works 👍

I wouldn't do that but sure

**Comment by itsmebombie** [comment]
that's what they all say
