### ISSUE TITLE
Make it easier to use custom particles

### ISSUE THREAD

**Issue by regestriryisa** [Spu7Nix/SPWN-language#334]
![Скриншот 24-01-2024 115704](https://github.com/Spu7Nix/SPWN-language/assets/110654477/f44d37f0-c426-47b9-a5d8-cc2cfca4f429)
Wtf

**Comment by SpeckyYT** [comment]
that's just how geometry dash works.

**Comment by regestriryisa** [comment]
> that's just how geometry dash works.

But it is possible for example to create built-in macro for this.

**Comment by SpeckyYT** [comment]
there is no reason for it to be built-in. if you want to parse it, do `.split("a")` and if you want to "serialize" it, do `.join("a")`.
