### ISSUE TITLE
$.readbin

### ISSUE THREAD

**Issue by s5bug** [Spu7Nix/SPWN-language#43]
`$.readfile` fails if the file is not valid UTF-8. I'm reading Pokémon Red map and tile data, which is not valid UTF-8.

Proposal: `$.readbin`. Returns the contents of the file as an array of bytes (`@number`s).

**Comment by SpeckyYT** [comment]
`$.readfile` could get an additional parameter for select the decoding.
e.g.
```rs
$.readfile("badapple.txt") // automatically goes for utf-8
$.readfile("pokemon.bin","binary")
$.readfile("rickrollimage.txt","ascii")
$.readfile("base64stuff.txt","base64")
$.readfile("hax.txt","hex")
// etc.
```

**Comment by Spu7Nix** [comment]
Implemented! You can now read binary files with `$.readfile("file.bin", "bin")`. More data formats can easily be added in the future.
