### ISSUE TITLE
Man Page

### ISSUE THREAD

**Issue by yavko** [Spu7Nix/SPWN-language#50]
There should be a man page. Idk for offline, and cli stuff idk would be nice.
----
<img width="202" alt="CleanShot 2021-07-20 at 16 44 19@2x" src="https://user-images.githubusercontent.com/15178513/126408819-138ac563-7992-4206-929b-7789b9fc0f5b.png">

**Comment by yavko** [comment]
Here is something I found [rust-cli/man](https://github.com/rust-cli/man)
If it isn't implemented I'll make it myself once I'm able to, (not soon).

**Comment by YaBoiMason** [comment]
i'd love this, i read manpages religiously

**Comment by krista-chan** [comment]
I made a script to install the man page @ [install_spwn_man.sh](https://gist.githubusercontent.com/krista-chan/a30d2704b3a8f5fc5bfd255ff3f760dc/raw/cbef857619574f9ff4b9a921d3cda6779536e704/install_spwn_man.sh)
