### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by Vainstains** [Spu7Nix/SPWN-language#73]
outputted this:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\main.rs:135:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

PS C:\Users\dbasp> 

i assume this means that it isnt allowed to write, but how do i allow it to?

**Comment by sertdfyguhi** [comment]
what command did u run

**Comment by robiot** [comment]
Well that unwrap should be handled, which it already seems to be, tho the error is ignored and it supposes that the file doesn't exist if any error occured. But did you try running it at sudo?

**Comment by SpeckyYT** [comment]
💀
